apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  # remote kustomize reference
  # - https://github.com/redhat-na-ssa/demo-ai-gitops-catalog/components/cluster-configs/console-config/overlays/default?ref=v0.19

  # kustomize build command
  # oc kustomize https://github.com/redhat-na-ssa/demo-ai-gitops-catalog/components/cluster-configs/console-config/overlays/default?ref=v0.19 > remote.yaml
  - remote.yaml

  - banner-demo.yaml
  - link-github.yaml
